# Generated by Django 5.2.4 on 2025-07-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], default='other', max_length=6),
        ),
    ]
